import type { Metadata } from "next";
import { Roboto, Figtree, Josefin_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./components/nav-bar";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Carter Moore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${figtree.variable} ${josefinSans.variable} antialiased max-w-screen-xl bg-background mx-auto`}
      >
        <NavBar/>
        {children}
        <footer className="font-body text-center my-6">Created by Carter Moore</footer>
      </body>
    </html>
  );
}
